name: CD
on:
  release:
    types: [created]
env:
  IMAGE: indeedhat/preorder-server
  TAG: ${{ github.event.release.tag_name }}
  REGISTRY_HOST: ghcr.io
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_PAT }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE }}:${{ env.TAG }}
          target: production
